print("My name is John Doe")
print("I am solving Problem 1 of Day 6.")
print("I love coding in Python.")
print("Let's build something amazing today!")
print("Happy coding!")
print("Keep pushing your limits!")