print("I am learning Python programming.")
print("This is Problem 3 of Day 6.")
print("I enjoy solving coding challenges.")
print("Let's keep pushing our limits!")
print("Happy coding!")
print("Keep pushing your limits!")
print("Happy coding!")